name = "BioDemultiplexer"
uuid = "39204792-bc26-423a-8bcf-54c03468b271"
authors = ["I.Mihara <issei.mihara@xforestx.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
